### ISSUE TITLE
udev rules reference nvidia-frontend module which is no longer present in drivers v 545.23.06 and onwards

### ISSUE THREAD

**Issue by scratchings** [NVIDIA/yum-packaging-nvidia-kmod-common#4]
OS Rocky Linux 9.4/A30 card
When the udev rules are triggered for the NVIDIA hardware the following error messages appear in /var/log/messages:

systemd-udevd[1193]: /usr/lib/udev/rules.d/60-nvidia.rules:2 Invalid value "/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'" for RUN (char 61: invalid substitution type), ignoring.
systemd-udevd[1193]: /usr/lib/udev/rules.d/60-nvidia.rules:3 Invalid value "/usr/bin/bash -c 'for i in $(cat /proc/driver/nvidia/gpus/*/information | grep Minor | cut -d \  -f 4); do /usr/bin/mknod -Z -m 666 /dev/nvidia${i} c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) ${i}; done'" for RUN (char 28: invalid substitution type), ignoring.
systemd-udevd[1193]: /usr/lib/udev/rules.d/60-nvidia.rules:4 Invalid value "/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidia-modeset c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 254'" for RUN (char 66: invalid substitution type), ignoring.
systemd-udevd[1193]: /usr/lib/udev/rules.d/60-nvidia.rules:5 Invalid value "/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidia-uvm c $(grep nvidia-uvm /proc/devices | cut -d \  -f 1) 0'" for RUN (char 62: invalid substitution type), ignoring.
systemd-udevd[1193]: /usr/lib/udev/rules.d/60-nvidia.rules:6 Invalid value "/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidia-uvm-tools c $(grep nvidia-uvm /proc/devices | cut -d \  -f 1) 1'" for RUN (char 68: invalid substitution type), ignoring.
kernel: nvidia 0000:81:00.0: enabling device (0000 -> 0002)
systemd-udevd[1201]: nvidia: Process '/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'' failed with exit code 1.
kernel: nvidia_fs: no symbol version for nvidia_p2p_dma_unmap_pages
systemd-udevd[1198]: nvidia: Process '/usr/bin/bash -c '/usr/bin/mknod -Z -m 666 /dev/nvidiactl c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 255'' failed with exit code 1.

As the mknod commands fail then there are no device special files for the GPU(s) and nvidia-smi reports:

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Comment by scaronni-nvidia** [comment]
`udev` rules have been reworked in driver 560 to use `nvidia-modprobe` to accomodate for all device types that can be available beside the basic ones. Latest code drop has been pushed to the 560 branch.
